export {default as img_seara} from './img_seara.png'
export {default as img_swift} from './img_swift.png'
export {default as img_friboi} from './img_friboi.png'
export {default as img_picpay} from './img_picpay.png'
export {default as img_original} from './img_original.png'