export * from './AboutUs';
export * from './Academic';
export * from './Admission';
export * from './Governance';
export * from './Home';
export * from './LazyLoading';
export * from './News';
export * from './VirtualTour';
export * from './AboutUs'
